version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directories:
      - /infra/docker
      - /infra/postgres
      - /deploy
      - /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
