packages:
  - apps/*
  - packages/*

minimumReleaseAge: 10080

allowBuilds:
  '@scarf/scarf': false
  argon2: true
  esbuild: true
  protobufjs: true
  sharp: true

overrides:
  '@grpc/grpc-js': '>=1.14.5 <2'
